# name: Terragrunt CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main

# jobs:
#   terragrunt:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Set up Terraform
#         uses: hashicorp/setup-terraform@v2
#         with:
#           terraform_version: 1.5.0

#       - name: Set up Terragrunt
#         run: |
#           wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.38.0/terragrunt_linux_amd64 -O /tmp/terragrunt
#           chmod +x /tmp/terragrunt
#           sudo mv /tmp/terragrunt /usr/local/bin/terragrunt

#       - name: Terragrunt Init
#         run: terragrunt run-all init
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         working-directory: live/us-east-1/dev

#       - name: Terragrunt Plan
#         run: terragrunt run-all plan -out=tfplan
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         working-directory: live/us-east-1/dev

#       - name: Terragrunt Apply (main branch only)
#         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#         run: terragrunt run-all apply tfplan
#         env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         working-directory: live/us-east-1/dev